### ISSUE TITLE
Loading circle in place of 'no stuff for sale'

### ISSUE THREAD

**Issue by dannyLister** [OpenClassrooms-Student-Center/5614116-go-fullstack-recipe-frontend#2]
stuff for sale doesn't seem to be connecting, just finished 'Create a GET route' and I still have the loading icon, (which has been present since the initial repo clone).
I have completed the chapter above expecting it to fix the issue, but to no avail.

![GET request](https://user-images.githubusercontent.com/43031765/60723764-77468b00-9f2c-11e9-8d9c-cb07d46566ab.PNG)

**Comment by willehpeh** [comment]
Hi,

The error shows you have made a mistake in accounting for CORS. Have a close look at your code and the error and you’ll see your mistake.

On 5 Jul 2019, at 14:55, Daniel Lister <notifications@github.com<mailto:notifications@github.com>> wrote:


stuff for sale doesn't seem to be connecting, just finished 'Create a GET route' and I still have the loading icon, (which has been present since the initial repo clone).
I have completed the chapter above expecting it to fix the issue, but to no avail.

[GET request]<https://user-images.githubusercontent.com/43031765/60723764-77468b00-9f2c-11e9-8d9c-cb07d46566ab.PNG>

**Comment by dannyLister** [comment]
Thanks for your quick response, found it: I had a typo:
![typo paint](https://user-images.githubusercontent.com/43031765/60725596-68aea280-9f31-11e9-9f44-d4bade9e850c.png)
